modify configure
Signed-off-by: Ji Bo <jibo@edan.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7207,11 +7207,11 @@ echo "$as_me: Enabling SITA ACN support" >&6;}
 
 else
 
-if test -z "$with_pcap" && test "$cross_compiling" = yes; then
-	{ { echo "$as_me:$LINENO: error: pcap type not determined when cross-compiling; use --with-pcap=..." >&5
-echo "$as_me: error: pcap type not determined when cross-compiling; use --with-pcap=..." >&2;}
-   { (exit 1); exit 1; }; }
-fi
+#if test -z "$with_pcap" && test "$cross_compiling" = yes; then
+#	{ { echo "$as_me:$LINENO: error: pcap type not determined when cross-compiling; use --with-pcap=..." >&5
+#echo "$as_me: error: pcap type not determined when cross-compiling; use --with-pcap=..." >&2;}
+#   { (exit 1); exit 1; }; }
+#fi
 
 # Check whether --with-pcap was given.
 if test "${with_pcap+set}" = set; then
